Create database Voealto;

Use Voealto;

CREATE TABLE ENDERECO (
ID_ENDERECO integer auto_increment primary key,
ID_CLIENTE INTEGER NOT NULL,
Logadouro VARCHAR(100) NOT NULL,
Estado VARCHAR(20) NOT NULL,
Cidade VARCHAR(20) NOT NULL
);

CREATE TABLE ORIGEM (
ID_ORIGEM INTEGER auto_increment PRIMARY KEY,
ID_PACOTE INTEGER,
ID_PROMOCAO INTEGER,
CIDADE VARCHAR(20) NOT NULL
);

CREATE TABLE PACOTE (
ID_PACOTE INTEGER auto_increment PRIMARY KEY,
ID_CLIENTE INTEGER,
ID_ORIGEM INTEGER,
ID_DESTINO INTEGER,
FOREIGN KEY(ID_ORIGEM) REFERENCES ORIGEM (ID_ORIGEM)
);

CREATE TABLE DESTINO (
ID_DESTINO INTEGER auto_increment PRIMARY KEY,
ID_PACOTE INTEGER,
ID_PROMOCAO INTEGER,
CIDADE VARCHAR(20) NOT null,
FOREIGN KEY(ID_PACOTE) REFERENCES PACOTE (ID_PACOTE)
);

CREATE TABLE PROMOÇÃO (
ID_PROMOCAO INTEGER auto_increment PRIMARY KEY,
ID_DESTINO INTEGER,
ID_ORIGEM INTEGER,
DESCONTO NUMERIC(2),
VALIDADE DATETIME ,
FOREIGN KEY(ID_DESTINO) REFERENCES DESTINO (ID_DESTINO),
FOREIGN KEY(ID_ORIGEM) REFERENCES ORIGEM (ID_ORIGEM)
);

CREATE TABLE CLIENTE (
ID_CLIENTE INTEGER auto_increment PRIMARY KEY,
ID_ENDERECO INTEGER,
ID_PACOTE INTEGER,
NOME VARCHAR(100) NOT null,
NASCIMENTO DATETIME,
EMAIL VARCHAR(40) NOT null,
SEXO CHAR(1),
TELEFONE numeric(14) NOT null,
FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO (ID_ENDERECO),
FOREIGN KEY(ID_PACOTE) REFERENCES PACOTE (ID_PACOTE)
);

ALTER TABLE ENDERECO ADD FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);
ALTER TABLE ORIGEM ADD FOREIGN KEY(ID_PACOTE) REFERENCES PACOTE (ID_PACOTE);
ALTER TABLE ORIGEM ADD FOREIGN KEY(ID_PROMOCAO) REFERENCES PROMOÇÃO (ID_PROMOCAO);
ALTER TABLE PACOTE ADD FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE);
ALTER TABLE PACOTE ADD FOREIGN KEY(ID_DESTINO) REFERENCES DESTINO (ID_DESTINO);
ALTER TABLE DESTINO ADD FOREIGN KEY(ID_PROMOCAO) REFERENCES PROMOÇÃO (ID_PROMOCAO)